name: Tests

on: 
 - push

 # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  run-tests:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2

    - name: Prepare dependencies
      run: npm install
    
    - name: Run tests
      run: npm test

    - name: Setup Pages
      if: always()
      uses: actions/configure-pages@v2
    - name: Upload artifact
      if: always()
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload entire repository
        path: './reports'
    - name: Deploy to GitHub Pages
      if: always()
      id: deployment
      uses: actions/deploy-pages@v1
